
library(argparse)
library(data.table)
library(jsonlite)

parser <- argparse::ArgumentParser()
parser$add_argument(
    "--file"
    , type = "character"
    , help = "JSON file generated by check_licenses.sh"
)

# Grab args (store in constants for easier debugging)
args <- parser$parse_args()
JSON_FILE <- args[["file"]]
OUT_FILE <- file.path(getwd(), "dependencies.csv")

licenseDT <- data.table::as.data.table(
    jsonlite::fromJSON(
        JSON_FILE
        , simplifyDataFrame = TRUE
    )
)
data.table::setorderv(licenseDT, "Name")
licenseDT <- licenseDT[, .(
    `Library Name` = Name
    , `Version in Use` = Version
    , License = License
    , URL = URL
)]
data.table::fwrite(
    x = licenseDT
    , file = OUT_FILE
)
